### PR TITLE
newly generated header+src, avoid "max" in global namespace

### PR DESCRIPTION
**Pull request by tlobig**
used this line to generate the suggested headers:
xsd cxx-tree --hxx-suffix .h --cxx-suffix .cpp --reserved-name access=parkingSpace_access --reserved-name link=lane_link --reserved-name max=t_max schema/OpenDRIVE_1.4H.xsd

this should have minimal impact on users of the library

### CODE REVIEW

**Comment by tlobig** [comment]
had to include one more reserved name: signal -> t_signal

**Comment by ArtistZhou** [comment]
> used this line to generate the suggested headers:
> xsd cxx-tree --hxx-suffix .h --cxx-suffix .cpp --reserved-name access=parkingSpace_access --reserved-name link=lane_link --reserved-name max=t_max schema/OpenDRIVE_1.4H.xsd
> 
> this should have minimal impact on users of the library

I find this problem too , i have a new issue when i use this hearder and cpp to write to file,I use this code `std::ofstream ofs(strodrMapPath.c_str());
	OpenDRIVE_(ofs, *m_pOdrHandle);`
it works fine ,but the attribute is ordered,which is not expect.
image
but i need the order like this one 
image
Do you have any idea do not  sort the key? sorry about my poor language

**Comment by tlobig** [comment]
Sorry @ArtistZhou I don't know if it is possible at all to keep the attribute order intact. I think from the XML-standard the order should not be relevant, since you should access all attributes by key. See https://stackoverflow.com/a/33746277
If the application which reads your XML-output expects a specific order, then it is not XML-standard compliant. I know this does not really help you. But at least you are not the only person with this problem:
https://www.codesynthesis.com/pipermail/xsd-users/2013-September/004079.html

**Comment by ArtistZhou** [comment]
> Sorry @ArtistZhou I don't know if it is possible at all to keep the attribute order intact. I think from the XML-standard the order should not be relevant, since you should access all attributes by key. See https://stackoverflow.com/a/33746277
> If the application which reads your XML-output expects a specific order, then it is not XML-standard compliant. I know this does not really help you. But at least you are not the only person with this problem:
> https://www.codesynthesis.com/pipermail/xsd-users/2013-September/004079.html

Thank you very much!Maybe i can write them into file with string if i want them  in  specific order

**Pull request merged**
